site_name: "KayakTransaction CSV Processing"
site_description: "User-friendly documentation powered by MkDocs."
site_url: "https://documentation-using-ai-agent.readthedocs.io"

theme:
  name: dracula
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  language: en
extra:
  favicon: assets/img/favicon.ico

repo_url: "https://github.com/M-E-U-E/Documentation-Using-AI-Agent"

nav:
  - Table of Contents: index.md
  - 1. Background: background.md
  - 2. Project’s Goal: project_goal.md
  - 3. Features: features.md
  - 4. Overview: overview.md
  - 5. Introduction: Introduction.md
  - 6. Prerequisites: prerequisites.md
  - 7. Setup:
      - 7.1. Project Setup: setup.md
      - 7.2. Setting up PostgreSQL: postgresql.md
  - 8. Project Structure: 
      - 8.1. Directory: project_structure.md
      - 8.2. Database: project_database.md
  - 9. Running Cron Jobs: running_cron_jobs.md
  - 10. Dependencies: dependencies.md
  - 11. Technologies Used: technologies.md
  
